package birdeye

import (
	"fmt"
)

type TokenOverview struct {
	Data struct {
		Address    string `json:"address"`
		Decimals   int    `json:"decimals"`
		Symbol     string `json:"symbol"`
		Name       string `json:"name"`
		Extensions struct {
			CoingeckoId string `json:"coingeckoId"`
			SerumV3Usdc string `json:"serumV3Usdc"`
			SerumV3Usdt string `json:"serumV3Usdt"`
			Website     string `json:"website"`
			Telegram    any    `json:"telegram"`
			Twitter     string `json:"twitter"`
			Description string `json:"description"`
			Discord     string `json:"discord"`
			Medium      string `json:"medium"`
		} `json:"extensions"`
		LogoURI                      string  `json:"logoURI"`
		Liquidity                    float64 `json:"liquidity"`
		LastTradeUnixTime            int64   `json:"lastTradeUnixTime"`
		LastTradeHumanTime           string  `json:"lastTradeHumanTime"`
		Price                        float64 `json:"price"`
		History30MPrice              float64 `json:"history30mPrice"`
		PriceChange30MPercent        float64 `json:"priceChange30mPercent"`
		History1HPrice               float64 `json:"history1hPrice"`
		PriceChange1HPercent         float64 `json:"priceChange1hPercent"`
		History2HPrice               float64 `json:"history2hPrice"`
		PriceChange2HPercent         float64 `json:"priceChange2hPercent"`
		History4HPrice               float64 `json:"history4hPrice"`
		PriceChange4HPercent         float64 `json:"priceChange4hPercent"`
		History6HPrice               float64 `json:"history6hPrice"`
		PriceChange6HPercent         float64 `json:"priceChange6hPercent"`
		History8HPrice               float64 `json:"history8hPrice"`
		PriceChange8HPercent         float64 `json:"priceChange8hPercent"`
		History12HPrice              float64 `json:"history12hPrice"`
		PriceChange12HPercent        float64 `json:"priceChange12hPercent"`
		History24HPrice              float64 `json:"history24hPrice"`
		PriceChange24HPercent        float64 `json:"priceChange24hPercent"`
		UniqueWallet30M              int     `json:"uniqueWallet30m"`
		UniqueWalletHistory30M       int     `json:"uniqueWalletHistory30m"`
		UniqueWallet30MChangePercent float64 `json:"uniqueWallet30mChangePercent"`
		UniqueWallet1H               int     `json:"uniqueWallet1h"`
		UniqueWalletHistory1H        int     `json:"uniqueWalletHistory1h"`
		UniqueWallet1HChangePercent  float64 `json:"uniqueWallet1hChangePercent"`
		UniqueWallet2H               int     `json:"uniqueWallet2h"`
		UniqueWalletHistory2H        int     `json:"uniqueWalletHistory2h"`
		UniqueWallet2HChangePercent  float64 `json:"uniqueWallet2hChangePercent"`
		UniqueWallet4H               int     `json:"uniqueWallet4h"`
		UniqueWalletHistory4H        int     `json:"uniqueWalletHistory4h"`
		UniqueWallet4HChangePercent  float64 `json:"uniqueWallet4hChangePercent"`
		UniqueWallet8H               int     `json:"uniqueWallet8h"`
		UniqueWalletHistory8H        int     `json:"uniqueWalletHistory8h"`
		UniqueWallet8HChangePercent  float64 `json:"uniqueWallet8hChangePercent"`
		UniqueWallet24H              int     `json:"uniqueWallet24h"`
		UniqueWalletHistory24H       int     `json:"uniqueWalletHistory24h"`
		UniqueWallet24HChangePercent float64 `json:"uniqueWallet24hChangePercent"`
		TotalSupply                  float64 `json:"totalSupply"`
		Fdv                          float64 `json:"fdv"`
		CirculatingSupply            float64 `json:"circulatingSupply"`
		MarketCap                    float64 `json:"marketCap"`
		Holder                       int     `json:"holder"`
		Trade30M                     int     `json:"trade30m"`
		TradeHistory30M              int     `json:"tradeHistory30m"`
		Trade30MChangePercent        float64 `json:"trade30mChangePercent"`
		Sell30M                      int     `json:"sell30m"`
		SellHistory30M               int     `json:"sellHistory30m"`
		Sell30MChangePercent         float64 `json:"sell30mChangePercent"`
		Buy30M                       int     `json:"buy30m"`
		BuyHistory30M                int     `json:"buyHistory30m"`
		Buy30MChangePercent          float64 `json:"buy30mChangePercent"`
		V30M                         float64 `json:"v30m"`
		V30MUSD                      float64 `json:"v30mUSD"`
		VHistory30M                  float64 `json:"vHistory30m"`
		VHistory30MUSD               float64 `json:"vHistory30mUSD"`
		V30MChangePercent            float64 `json:"v30mChangePercent"`
		VBuy30M                      float64 `json:"vBuy30m"`
		VBuy30MUSD                   float64 `json:"vBuy30mUSD"`
		VBuyHistory30M               float64 `json:"vBuyHistory30m"`
		VBuyHistory30MUSD            float64 `json:"vBuyHistory30mUSD"`
		VBuy30MChangePercent         float64 `json:"vBuy30mChangePercent"`
		VSell30M                     float64 `json:"vSell30m"`
		VSell30MUSD                  float64 `json:"vSell30mUSD"`
		VSellHistory30M              float64 `json:"vSellHistory30m"`
		VSellHistory30MUSD           float64 `json:"vSellHistory30mUSD"`
		VSell30MChangePercent        float64 `json:"vSell30mChangePercent"`
		Trade1H                      int     `json:"trade1h"`
		TradeHistory1H               int     `json:"tradeHistory1h"`
		Trade1HChangePercent         float64 `json:"trade1hChangePercent"`
		Sell1H                       int     `json:"sell1h"`
		SellHistory1H                int     `json:"sellHistory1h"`
		Sell1HChangePercent          float64 `json:"sell1hChangePercent"`
		Buy1H                        int     `json:"buy1h"`
		BuyHistory1H                 int     `json:"buyHistory1h"`
		Buy1HChangePercent           float64 `json:"buy1hChangePercent"`
		V1H                          float64 `json:"v1h"`
		V1HUSD                       float64 `json:"v1hUSD"`
		VHistory1H                   float64 `json:"vHistory1h"`
		VHistory1HUSD                float64 `json:"vHistory1hUSD"`
		V1HChangePercent             float64 `json:"v1hChangePercent"`
		VBuy1H                       float64 `json:"vBuy1h"`
		VBuy1HUSD                    float64 `json:"vBuy1hUSD"`
		VBuyHistory1H                float64 `json:"vBuyHistory1h"`
		VBuyHistory1HUSD             float64 `json:"vBuyHistory1hUSD"`
		VBuy1HChangePercent          float64 `json:"vBuy1hChangePercent"`
		VSell1H                      float64 `json:"vSell1h"`
		VSell1HUSD                   float64 `json:"vSell1hUSD"`
		VSellHistory1H               float64 `json:"vSellHistory1h"`
		VSellHistory1HUSD            float64 `json:"vSellHistory1hUSD"`
		VSell1HChangePercent         float64 `json:"vSell1hChangePercent"`
		Trade2H                      int     `json:"trade2h"`
		TradeHistory2H               int     `json:"tradeHistory2h"`
		Trade2HChangePercent         float64 `json:"trade2hChangePercent"`
		Sell2H                       int     `json:"sell2h"`
		SellHistory2H                int     `json:"sellHistory2h"`
		Sell2HChangePercent          float64 `json:"sell2hChangePercent"`
		Buy2H                        int     `json:"buy2h"`
		BuyHistory2H                 int     `json:"buyHistory2h"`
		Buy2HChangePercent           float64 `json:"buy2hChangePercent"`
		V2H                          float64 `json:"v2h"`
		V2HUSD                       float64 `json:"v2hUSD"`
		VHistory2H                   float64 `json:"vHistory2h"`
		VHistory2HUSD                float64 `json:"vHistory2hUSD"`
		V2HChangePercent             float64 `json:"v2hChangePercent"`
		VBuy2H                       float64 `json:"vBuy2h"`
		VBuy2HUSD                    float64 `json:"vBuy2hUSD"`
		VBuyHistory2H                float64 `json:"vBuyHistory2h"`
		VBuyHistory2HUSD             float64 `json:"vBuyHistory2hUSD"`
		VBuy2HChangePercent          float64 `json:"vBuy2hChangePercent"`
		VSell2H                      float64 `json:"vSell2h"`
		VSell2HUSD                   float64 `json:"vSell2hUSD"`
		VSellHistory2H               float64 `json:"vSellHistory2h"`
		VSellHistory2HUSD            float64 `json:"vSellHistory2hUSD"`
		VSell2HChangePercent         float64 `json:"vSell2hChangePercent"`
		Trade4H                      int     `json:"trade4h"`
		TradeHistory4H               int     `json:"tradeHistory4h"`
		Trade4HChangePercent         float64 `json:"trade4hChangePercent"`
		Sell4H                       int     `json:"sell4h"`
		SellHistory4H                int     `json:"sellHistory4h"`
		Sell4HChangePercent          float64 `json:"sell4hChangePercent"`
		Buy4H                        int     `json:"buy4h"`
		BuyHistory4H                 int     `json:"buyHistory4h"`
		Buy4HChangePercent           float64 `json:"buy4hChangePercent"`
		V4H                          float64 `json:"v4h"`
		V4HUSD                       float64 `json:"v4hUSD"`
		VHistory4H                   float64 `json:"vHistory4h"`
		VHistory4HUSD                float64 `json:"vHistory4hUSD"`
		V4HChangePercent             float64 `json:"v4hChangePercent"`
		VBuy4H                       float64 `json:"vBuy4h"`
		VBuy4HUSD                    float64 `json:"vBuy4hUSD"`
		VBuyHistory4H                float64 `json:"vBuyHistory4h"`
		VBuyHistory4HUSD             float64 `json:"vBuyHistory4hUSD"`
		VBuy4HChangePercent          float64 `json:"vBuy4hChangePercent"`
		VSell4H                      float64 `json:"vSell4h"`
		VSell4HUSD                   float64 `json:"vSell4hUSD"`
		VSellHistory4H               float64 `json:"vSellHistory4h"`
		VSellHistory4HUSD            float64 `json:"vSellHistory4hUSD"`
		VSell4HChangePercent         float64 `json:"vSell4hChangePercent"`
		Trade8H                      int     `json:"trade8h"`
		TradeHistory8H               int     `json:"tradeHistory8h"`
		Trade8HChangePercent         float64 `json:"trade8hChangePercent"`
		Sell8H                       int     `json:"sell8h"`
		SellHistory8H                int     `json:"sellHistory8h"`
		Sell8HChangePercent          float64 `json:"sell8hChangePercent"`
		Buy8H                        int     `json:"buy8h"`
		BuyHistory8H                 int     `json:"buyHistory8h"`
		Buy8HChangePercent           float64 `json:"buy8hChangePercent"`
		V8H                          float64 `json:"v8h"`
		V8HUSD                       float64 `json:"v8hUSD"`
		VHistory8H                   float64 `json:"vHistory8h"`
		VHistory8HUSD                float64 `json:"vHistory8hUSD"`
		V8HChangePercent             float64 `json:"v8hChangePercent"`
		VBuy8H                       float64 `json:"vBuy8h"`
		VBuy8HUSD                    float64 `json:"vBuy8hUSD"`
		VBuyHistory8H                float64 `json:"vBuyHistory8h"`
		VBuyHistory8HUSD             float64 `json:"vBuyHistory8hUSD"`
		VBuy8HChangePercent          float64 `json:"vBuy8hChangePercent"`
		VSell8H                      float64 `json:"vSell8h"`
		VSell8HUSD                   float64 `json:"vSell8hUSD"`
		VSellHistory8H               float64 `json:"vSellHistory8h"`
		VSellHistory8HUSD            float64 `json:"vSellHistory8hUSD"`
		VSell8HChangePercent         float64 `json:"vSell8hChangePercent"`
		Trade24H                     int     `json:"trade24h"`
		TradeHistory24H              int     `json:"tradeHistory24h"`
		Trade24HChangePercent        float64 `json:"trade24hChangePercent"`
		Sell24H                      int     `json:"sell24h"`
		SellHistory24H               int     `json:"sellHistory24h"`
		Sell24HChangePercent         float64 `json:"sell24hChangePercent"`
		Buy24H                       int     `json:"buy24h"`
		BuyHistory24H                int     `json:"buyHistory24h"`
		Buy24HChangePercent          float64 `json:"buy24hChangePercent"`
		V24H                         float64 `json:"v24h"`
		V24HUSD                      float64 `json:"v24hUSD"`
		VHistory24H                  float64 `json:"vHistory24h"`
		VHistory24HUSD               float64 `json:"vHistory24hUSD"`
		V24HChangePercent            float64 `json:"v24hChangePercent"`
		VBuy24H                      float64 `json:"vBuy24h"`
		VBuy24HUSD                   float64 `json:"vBuy24hUSD"`
		VBuyHistory24H               float64 `json:"vBuyHistory24h"`
		VBuyHistory24HUSD            float64 `json:"vBuyHistory24hUSD"`
		VBuy24HChangePercent         float64 `json:"vBuy24hChangePercent"`
		VSell24H                     float64 `json:"vSell24h"`
		VSell24HUSD                  float64 `json:"vSell24hUSD"`
		VSellHistory24H              float64 `json:"vSellHistory24h"`
		VSellHistory24HUSD           float64 `json:"vSellHistory24hUSD"`
		VSell24HChangePercent        float64 `json:"vSell24hChangePercent"`
		NumberMarkets                int     `json:"numberMarkets"`
	} `json:"data"`
	Success bool `json:"success"`
}

func (srv *Client) GetOverview(address string) (*TokenOverview, error) {
	url := fmt.Sprintf("%s/token_overview?address=%s", baseURL, address)
	return newCli[TokenOverview](srv.apiKey).makeRequest("GET", url, nil)
}
